"""Add user_bot_controls table

Revision ID: 1ee2139cb14e
Revises: ed216d3f00c3
Create Date: 2025-11-15 17:49:01.820428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee2139cb14e'
down_revision: Union[str, Sequence[str], None] = 'ed216d3f00c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_loaimay'), table_name='services')
    op.drop_index(op.f('ix_services_thuonghieu'), table_name='services')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_services_thuonghieu'), 'services', ['thuonghieu'], unique=False)
    op.create_index(op.f('ix_services_loaimay'), 'services', ['loaimay'], unique=False)
    # ### end Alembic commands ###
